apiVersion: v1
kind: Service
metadata:
  name: haubzit-backend
  labels:
    appl: haubzit-backend
spec:
  selector:
    appl: haubzit-backend
  type: NodePort
  ports:
    - name: rest
      port: 8080
      protocol: TCP
      targetPort: rest
    - name: socket
      port: 9092
      targetPort: socket
