apiVersion: v1
kind: Service
metadata:
  name: haubzit-frontend
  labels:
    appl: haubzit-frontend
spec:
  selector:
    appl: haubzit-frontend
  type: NodePort
  ports:
    - name: frontend
      port: 80
      protocol: TCP
      targetPort: 80