apiVersion: v1
kind: Service
metadata:
  name: haubzit-postgres
  labels:
    appl: haubzit-postgres
spec:
  selector:
    appl: haubzit-postgres
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432