INSERT INTO OPTION (name, possession, zone, category, duel, pass, shoot, duel_def, pass_def,
                    shoot_def, risk, win, win_chance, loss, loss_chance, card_risk)
VALUES ('Pass', TRUE, 4, NULL, 10, 75, 10, NULL, NULL, NULL, NULL, 'ZONES_1', 75, 'BALL_LOSE', NULL,
        NULL),
       ('Pass', TRUE, 3, NULL, 10, 80, 10, NULL, NULL, NULL, NULL, 'ZONES_1', 85, 'BALL_LOSE', NULL,
        NULL),
       ('Pass', TRUE, 2, NULL, 10, 90, 10, NULL, NULL, NULL, NULL, 'ZONES_1', 90, 'BALL_LOSE', NULL,
        NULL),
       ('Pass', TRUE, 1, NULL, 10, 95, 10, NULL, NULL, NULL, NULL, 'ZONES_1', 95, 'GOAL_ENEMY',
        NULL, NULL),
       ('Schuss blocken', FALSE, 2, NULL, NULL, NULL, NULL, 10, 75, 10, NULL, 'BALL_POSSESSION', 20,
        NULL, NULL, NULL),
       ('Schuss blocken', FALSE, 1, NULL, NULL, NULL, NULL, 10, 75, 10, NULL, 'BALL_POSSESSION', 10,
        NULL, NULL, NULL),
       ('Grätsch', FALSE, 3, NULL, NULL, NULL, NULL, 70, 15, 10, 10, 'BALL_POSSESSION', 30, NULL,
        NULL, NULL),
       ('Grätsch', FALSE, 2, NULL, NULL, NULL, NULL, 75, 10, 10, 20, 'BALL_POSSESSION', 25, 'KICK',
        NULL, 15),
       ('Grätsch', FALSE, 1, NULL, NULL, NULL, NULL, 80, 10, 10, 30, 'BALL_POSSESSION', 20,
        'PENALTY', NULL, 20),
       ('Kläre', TRUE, 2, NULL, 10, 70, 10, NULL, NULL, NULL, NULL, 'ZONES_2', 10, 'BALL_LOSE',
        NULL, NULL),
       ('Kläre', TRUE, 1, NULL, 10, 65, 10, NULL, NULL, NULL, NULL, 'ZONES_2', 25, 'BALL_LOSE',
        NULL, NULL),
       ('Klärversuch blocke', FALSE, 4, NULL, NULL, NULL, NULL, 10, 65, 10, NULL, 'BALL_POSSESSION',
        10, NULL, NULL, NULL),
       ('Klärversuch blocke', FALSE, 5, NULL, NULL, NULL, NULL, 10, 60, 10, NULL,
        'NO_ZONE_WIN_ENEMY', 5, NULL, NULL, NULL),
       ('Tackling', FALSE, 5, NULL, NULL, NULL, NULL, 85, 20, 10, 5, 'BALL_POSSESSION', 10, NULL,
        NULL, NULL),
       ('Tackling', FALSE, 4, NULL, NULL, NULL, NULL, 80, 15, 10, 10, 'BALL_POSSESSION', 15, NULL,
        NULL, NULL),
       ('Tackling', FALSE, 3, NULL, NULL, NULL, NULL, 75, 10, 10, 15, 'BALL_POSSESSION', 25, NULL,
        NULL, NULL),
       ('Tackling', FALSE, 2, NULL, NULL, NULL, NULL, 60, 10, 10, 25, 'BALL_POSSESSION', 30, NULL,
        NULL, NULL),
       ('Tackling', FALSE, 1, NULL, NULL, NULL, NULL, 55, 10, 10, 35, 'BALL_POSSESSION', 30, NULL,
        NULL, NULL),
       ('Einrücke', FALSE, 2, NULL, NULL, NULL, NULL, 10, 65, 10, 10, 'BALL_POSSESSION', 20, NULL,
        NULL, NULL),
       ('Einrücke', FALSE, 1, NULL, NULL, NULL, NULL, 10, 70, 10, 15, 'BALL_POSSESSION', 15, NULL,
        NULL, NULL),
       ('Ball ablaufen', FALSE, 2, NULL, NULL, NULL, NULL, 10, 75, 10, 5, 'BALL_POSSESSION', 80,
        NULL, NULL, NULL),
       ('Ball ablaufen', FALSE, 1, NULL, NULL, NULL, NULL, 10, 85, 10, 5, 'BALL_POSSESSION', 90,
        NULL, NULL, NULL),
       ('Kopfball', FALSE, 2, NULL, NULL, NULL, NULL, 10, 70, 10, 5, 'BALL_POSSESSION', 70,
        'ZONES_1', 30, NULL),
       ('Kopfball', FALSE, 1, NULL, NULL, NULL, NULL, 10, 80, 10, 10, 'BALL_POSSESSION', 75,
        'ZONES_1', 25, NULL),
       ('Reinspringen', FALSE, 4, NULL, NULL, NULL, NULL, 10, 65, 10, 5, 'BALL_POSSESSION', 5, NULL,
        NULL, NULL),
       ('Reinspringen', FALSE, 3, NULL, NULL, NULL, NULL, 10, 55, 10, 10, 'BALL_POSSESSION', 5,
        NULL, NULL, NULL),
       ('Reinspringen', FALSE, 2, NULL, NULL, NULL, NULL, 10, 50, 10, 15, 'BALL_POSSESSION', 10,
        NULL, NULL, NULL),
       ('Reinspringen', FALSE, 1, NULL, NULL, NULL, NULL, 10, 45, 10, 25, 'BALL_POSSESSION', 15,
        NULL, NULL, NULL),
       ('Weitschuss antäusche', TRUE, 4, NULL, 70, 10, 10, NULL, NULL, NULL, NULL, 'ZONES_1', 60,
        NULL, NULL, NULL),
       ('langer Ball antäusche', TRUE, 3, NULL, 75, 10, 10, NULL, NULL, NULL, NULL, 'ZONES_1', 55,
        NULL, NULL, NULL),
       ('Pass antizipieren', FALSE, 4, NULL, NULL, NULL, NULL, 10, 85, 10, NULL, 'BALL_POSSESSION',
        NULL, NULL, NULL, NULL),
       ('Pass antizipieren', FALSE, 3, NULL, NULL, NULL, NULL, 10, 80, 10, 5, 'BALL_POSSESSION', 15,
        NULL, NULL, NULL),
       ('Pass antizipieren', FALSE, 2, NULL, NULL, NULL, NULL, 10, 70, 10, 20, 'BALL_POSSESSION',
        10, NULL, NULL, NULL),
       ('langer Ball', TRUE, 2, NULL, 10, 65, 10, NULL, NULL, NULL, NULL, 'ZONES_2', 60, NULL, NULL,
        NULL),
       ('langer Ball', TRUE, 1, NULL, 10, 75, 10, NULL, NULL, NULL, NULL, 'ZONES_2', 40, NULL, NULL,
        NULL),
       ('langer Ball blocken', FALSE, 5, NULL, NULL, NULL, NULL, 10, 75, 10, NULL, NULL, 5, NULL,
        NULL, NULL),
       ('langer Ball blocken', FALSE, 4, NULL, NULL, NULL, NULL, 10, 70, 10, NULL,
        'BALL_POSSESSION', 10, NULL, NULL, NULL),
       ('Dribbling', TRUE, 1, NULL, 70, 10, 10, NULL, NULL, NULL, 15, 'ZONES_1', 80, 'BALL_LOSE',
        NULL, NULL),
       ('Dribbling', TRUE, 2, NULL, 75, 10, 10, NULL, NULL, NULL, 10, 'ZONES_1', 70, 'BALL_LOSE',
        NULL, NULL),
       ('Dribbling', TRUE, 3, NULL, 80, 10, 10, NULL, NULL, NULL, 5, 'ZONES_1', 60, 'BALL_LOSE',
        NULL, NULL),
       ('Dribbling', TRUE, 4, NULL, 85, 10, 10, NULL, NULL, NULL, NULL, 'ZONES_1', 55, 'BALL_LOSE',
        NULL, NULL),
       ('Schnittstellenpass', TRUE, 4, NULL, 10, 90, 10, NULL, NULL, NULL, NULL, 'ZONES_2', 40,
        'BALL_LOSE', NULL, NULL),
       ('Steilpass in Schnittstelle', TRUE, 3, NULL, 10, 80, 10, NULL, NULL, NULL, NULL, 'ZONES_1',
        35, 'BALL_LOSE', NULL, NULL),
       ('Weitschuss', TRUE, 4, NULL, 10, 10, 65, NULL, NULL, NULL, NULL, 'GOAL', 10, NULL, NULL,
        NULL),
       ('Flanke', TRUE, 4, NULL, 10, 75, 10, NULL, NULL, NULL, NULL, 'ZONES_1', 60, NULL, NULL,
        NULL),
       ('weite Flanke', TRUE, 3, NULL, 10, 65, 10, NULL, NULL, NULL, NULL, 'ZONES_2', 30, NULL,
        NULL, NULL),
       ('Querpass', TRUE, 2, NULL, 10, 95, 10, NULL, NULL, NULL, NULL, 'NEW_SITUATION', 95, NULL,
        NULL, NULL),
       ('Querpass', TRUE, 3, NULL, 10, 95, 10, NULL, NULL, NULL, NULL, 'NEW_SITUATION', 90, NULL,
        NULL, NULL),
       ('Gegenpressing', FALSE, 5, NULL, NULL, NULL, NULL, 90, 10, 10, NULL, 'BALL_POSSESSION', 10,
        NULL, NULL, NULL),
       ('Gegenpressing', FALSE, 4, NULL, NULL, NULL, NULL, 80, 10, 10, NULL, 'BALL_POSSESSION', 25,
        NULL, NULL, NULL),
       ('Gegenpressing', FALSE, 3, NULL, NULL, NULL, NULL, 80, 10, 10, NULL, 'BALL_POSSESSION', 40,
        NULL, NULL, NULL),
       ('Schuss von Mittellinie', TRUE, 3, 'JOKER', 10, 10, 99, NULL, NULL, NULL, NULL, 'GOAL',
        NULL, NULL, NULL, NULL),
       ('Blutgrätsch', FALSE, 2, 'JOKER', NULL, NULL, NULL, 95, 10, 10, NULL, 'BALL_POSSESSION',
        NULL, NULL, NULL, NULL),
       ('No-Look Pass', TRUE, 3, 'JOKER', 10, 90, 10, NULL, NULL, NULL, NULL, 'ZONES_2', NULL, NULL,
        NULL, NULL),
       ('Tunnel und Antritt', TRUE, 3, 'JOKER', 95, 10, 10, NULL, NULL, NULL, NULL, 'ZONES_2', NULL,
        NULL, NULL, NULL),
       ('Tunnel und Schuss', TRUE, 4, 'JOKER', 10, 10, 95, NULL, NULL, NULL, NULL, 'GOAL_SHOT',
        NULL, NULL, NULL, NULL),
       ('Fallrückziehe', TRUE, 5, 'JOKER', 10, 10, 90, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL),
       ('Eigen GOAL', NULL, NULL, 'SPECIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL),
       ('Lattenschuss', NULL, NULL, 'SPECIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL),
       ('Pfostenschuss', NULL, NULL, 'SPECIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL),
       ('Penalty', NULL, NULL, 'SPECIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL),
       ('Eckball', NULL, NULL, 'SPECIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL);