version: '2.1'
services:
  postgresql:
    image: postgres:11-alpine
    container_name: butcher_postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=butcher
      - POSTGRES_PASSWORD=butcher
    networks:
      - frontend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U butcher" ]
      interval: 3s
      timeout: 2s
      retries: 10
networks:
  frontend:
